import { Outfit } from "next/font/google";
import "./globals.css";
import { assets } from "@/Assets/assets";

const outfit = Outfit({ subsets: ["latin"], weight:["400", "500", "600", "700"] });

export const metadata = {
  title: "lallala Diary",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" href="@/Assets/favicon.png"></link>
      </head>
      <body className={outfit.className}>{children}</body>
    </html>
  );
}
